#!/usr/bin/env bash
set -euo pipefail

# Run the Intern MCP against an active Aster stack in a Firstlanding worktree.
# All diagnostics go to stderr because `serve` reserves stdout for MCP stdio.

workspace=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
platform_workspace=${INTERN_PLATFORM_WORKSPACE:-}
aster_bin=${ASTER_BIN:-aster}
command=${1:-serve}

case "$command" in
  serve|login|logout|status) ;;
  *)
    echo "usage: $0 [serve|login|logout|status]" >&2
    exit 2
    ;;
esac

for dependency in "$aster_bin" node npm curl ssh ssh-keygen; do
  command -v "$dependency" >/dev/null 2>&1 || {
    echo "$dependency is required" >&2
    exit 1
  }
done

if [[ -z "$platform_workspace" || ! -f "$platform_workspace/aster.toml" ]]; then
  echo "INTERN_PLATFORM_WORKSPACE must point to the active Firstlanding worktree." >&2
  echo "Example: INTERN_PLATFORM_WORKSPACE=../firstlanding scripts/run-local.sh" >&2
  exit 1
fi
platform_workspace=$(cd "$platform_workspace" && pwd)

cd "$platform_workspace"
if ! ports_json=$($aster_bin --json services ports 2>/dev/null); then
  echo "Aster's service-port report is unavailable." >&2
  echo "Install Aster 0.11.1 or newer, then start the stack with:" >&2
  echo "  aster services up intern-local" >&2
  exit 1
fi

ports=$(printf '%s' "$ports_json" | node --input-type=module -e '
  const chunks = [];
  for await (const chunk of process.stdin) chunks.push(chunk);
  const report = JSON.parse(chunks.join(""));
  const candidates = (report.instances ?? []).filter((instance) => {
    if (instance.status !== "active") return false;
    const names = new Set((instance.services ?? []).map((service) => service.name));
    return names.has("intern-fe");
  });
  if (candidates.length === 0) {
    console.error("No active Aster supervisor contains intern-fe.");
    process.exit(3);
  }
  if (candidates.length > 1) {
    console.error("Multiple active Intern stacks exist in this worktree; stop the unused supervisor first.");
    process.exit(4);
  }
  const instance = candidates[0];
  const servicePort = (name) => {
    const service = instance.services.find((candidate) => candidate.name === name);
    return service?.port ?? (service?.port_name ? instance.ports?.[service.port_name] : undefined);
  };
  // Use the Aster worktree allocation instead of assuming default local ports.
  const platform = instance.ports?.platform;
  const frontend = servicePort("intern-fe");
  // Aster 0.11 reports selected service ports. The SSH listener is an
  // auxiliary port derived from the same worktree Platform allocation.
  const gatewaySSH = instance.ports?.["intern-gateway-ssh"] ?? 2222 + Math.max(platform - 4000, 0);
  const validPort = (port) => Number.isInteger(port) && port >= 1 && port <= 65535;
  if (!validPort(platform) || !validPort(frontend) || !validPort(gatewaySSH)) {
    console.error("The active Intern stack did not report its platform, intern-fe, and intern-gateway-ssh ports.");
    process.exit(5);
  }
  process.stdout.write(`${platform} ${frontend} ${gatewaySSH} ${instance.supervisor_pid}`);
') || {
  echo "Start exactly one local Intern stack with:" >&2
  echo "  aster services up intern        # Devbox-backed sites" >&2
  echo "  aster services up intern-local  # local intern-data" >&2
  exit 1
}
read -r platform_port frontend_port gateway_ssh_port supervisor_pid <<<"$ports"

local_env=${INTERN_LOCAL_ENV_FILE:-"$workspace/.env.intern.local"}
if [[ ! -f "$local_env" ]]; then
  echo "$local_env is missing." >&2
  echo "Provision the local Intern app and OAuth client once with:" >&2
  printf '  ARCHASTRO_API_URL=http://127.0.0.1:%s INTERN_PUBLIC_ORIGIN=http://127.0.0.1:%s INTERN_SERVICE_ENV_FILE=%q %q\n' \
    "$platform_port" "$frontend_port" "$local_env" "$platform_workspace/scripts/intern/setup-archastro-local.sh" >&2
  exit 1
fi

# This file is generated by Firstlanding's setup-archastro-local.sh with mode
# 0600 and contains
# only local public app/client identifiers plus the local org ID.
set -a
source "$local_env"
set +a

: "${ARCHASTRO_PUBLISHABLE_KEY:?ARCHASTRO_PUBLISHABLE_KEY is missing from .env.intern.local}"
: "${INTERN_OAUTH_CLIENT_ID:?INTERN_OAUTH_CLIENT_ID is missing from .env.intern.local}"

export ARCHASTRO_API_URL="http://127.0.0.1:$platform_port"
export INTERN_BASE_URL="http://127.0.0.1:$frontend_port"
export INTERN_CONFIG_ROOT=${INTERN_CONFIG_ROOT:-"$workspace/tmp/intern-mcp-local/config"}
export INTERN_WORKSPACE_ROOT=${INTERN_WORKSPACE_ROOT:-"$workspace/tmp/intern-mcp-local/sites"}
if [[ -z ${INTERN_GIT_SSH_COMMAND:-} ]]; then
  local_ssh_key="$INTERN_CONFIG_ROOT/id_ed25519"
  if [[ ! -f "$local_ssh_key" ]]; then
    mkdir -p "$INTERN_CONFIG_ROOT"
    chmod 700 "$INTERN_CONFIG_ROOT"
    ssh-keygen -q -t ed25519 -N '' -C intern-mcp-local -f "$local_ssh_key"
  fi
  printf -v local_ssh_key_quoted '%q' "$local_ssh_key"
  export INTERN_GIT_SSH_COMMAND="ssh -i $local_ssh_key_quoted -o IdentitiesOnly=yes -p $gateway_ssh_port -o HostName=127.0.0.1 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
fi

expected_device_uri="$INTERN_BASE_URL/device"
if [[ ${INTERN_DEVICE_VERIFICATION_URI:-} != "$expected_device_uri" ]]; then
  echo "The local OAuth client is not registered for this worktree's TryIntern port." >&2
  echo "Reconcile it with:" >&2
  printf '  ARCHASTRO_API_URL=%q INTERN_PUBLIC_ORIGIN=%q INTERN_SERVICE_ENV_FILE=%q %q\n' \
    "$ARCHASTRO_API_URL" "$INTERN_BASE_URL" "$local_env" "$platform_workspace/scripts/intern/setup-archastro-local.sh" >&2
  exit 1
fi

curl --noproxy '*' --fail --silent --show-error \
  "$ARCHASTRO_API_URL/healthz" >/dev/null || {
  echo "Platform is not healthy at $ARCHASTRO_API_URL (Aster supervisor $supervisor_pid)." >&2
  exit 1
}
curl --noproxy '*' --fail --silent --show-error \
  "$INTERN_BASE_URL/login" >/dev/null || {
  echo "TryIntern is not healthy at $INTERN_BASE_URL (Aster supervisor $supervisor_pid)." >&2
  exit 1
}

echo "Intern MCP local target:" >&2
echo "  TryIntern: $INTERN_BASE_URL" >&2
echo "  Platform:  $ARCHASTRO_API_URL" >&2
echo "  Sites:     $INTERN_WORKSPACE_ROOT" >&2
echo "  Git SSH:   127.0.0.1:$gateway_ssh_port" >&2
echo "  Aster PID: $supervisor_pid" >&2

cd "$workspace"
npm run build >&2
exec node "$workspace/dist/index.js" "$command"
